# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Phatt
logo:             <img src="images/phatt-logo.png"/>
tagline:          'Phatt'
description:      'Be Bold. Be Fierce. Be Phatt.'
url:              https://vorpalchic.github.io
baseurl:          /

author:
  name:           'Belinda Luce'
  url:            https://twitter.com/#

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/#
