# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Phatt
logo:             <img src="images/phatt-logo.png"/>
tagline:          'Be Bold. Be Fierce. Be Phatt.'
description:      'A blog about my fitness and health journey, by Belinda Luce.'
url:              https://vorpalchic.github.io
baseurl:          /

author:
  name:           'Belinda Luce'
  url:            https://twitter.com/#

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/#
